[package]
name = "food-lemmih-com-e2e-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
thirtyfour = "0.36.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
